export const activityFilters = {
  hiking: {
    Difficulty: ["Easy 🟢", "Moderate 🟡", "Challenging 🔴", "Expert ⚫"],
    Terrain: [
      "Forest 🌲",
      "Mountain ⛰️",
      "Coastal 🏖️",
      "Desert 🏜️",
      "Urban 🏙️",
    ],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Evening 🌆", "Night 🌙"],
    "Trail Length": [
      "Short (<2h) ⏱️",
      "Medium (2-4h) ➡️",
      "Long (4-6h) 🏁",
      "Full Day 🌞",
    ],
  },
  beaches: {
    Type: [
      "Sandy 🏖️",
      "Rocky 🪨",
      "Coral Reef 🐠",
      "Surf Beach 🏄",
      "Private Beach 🏝️",
    ],
    Activities: [
      "Swimming 🏊",
      "Snorkeling 🤿",
      "Surfing 🏄",
      "Sunbathing ☀️",
      "Beach Sports 🏐",
    ],
    Amenities: [
      "Beach Umbrellas ⛱️",
      "Restrooms 🚻",
      "Food Vendors 🍔",
      "Rental Equipment 🏄",
      "Lifeguards 🦺",
    ],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Sunset 🌅", "All Day 🌞"],
  },
  wildlife: {
    "Animal Focus": [
      "Marine Life 🐋",
      "Big Cats 🦁",
      "Elephants 🐘",
      "Birds 🐦",
      "Primates 🐒",
    ],
    "Tour Type": [
      "Safari 🚗",
      "Wildlife Park 🦁",
      "Sanctuary 🐘",
      "Conservation Center 🦒",
      "Bird Watching 🦜",
    ],
    Duration: ["Half Day ⏱️", "Full Day ☀️", "Overnight 🌙", "Multi-day 🏕️"],
    "Best Time": ["Dawn 🌅", "Dusk 🌆", "Night 🌙", "All Day 🌞"],
  },
  camping: {
    "Camp Type": [
      "Tent ⛺",
      "Cabin 🏡",
      "Glamping ⭐",
      "RV 🚐",
      "Backcountry 🏕️",
    ],
    Facilities: [
      "Campfire 🔥",
      "Restrooms 🚻",
      "Electricity 🔌",
      "Kitchen 🍳",
      "Showers 🚿",
    ],
    Location: [
      "Forest 🌲",
      "Mountain ⛰️",
      "Lakeside 🏞️",
      "Desert 🏜️",
      "Coastal 🏖️",
    ],
    "Best Season": ["Spring 🌸", "Summer ☀️", "Fall 🍂", "Winter ❄️"],
  },
  waterSports: {
    "Sport Type": [
      "Surfing 🏄",
      "Diving 🤿",
      "Sailing ⛵",
      "Kayaking 🛶",
      "Paddleboarding 🏄",
    ],
    "Experience Level": [
      "Beginner 🟢",
      "Intermediate 🟡",
      "Advanced 🔴",
      "Professional ⚫",
    ],
    "Water Type": ["Ocean 🌊", "Lake 🏞️", "River 🌊", "Lagoon 🏖️"],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Sunset 🌅", "All Day 🌞"],
  },
  historical: {
    Era: [
      "Ancient 🗿",
      "Medieval 🏰",
      "Renaissance 🎨",
      "Colonial 🏛️",
      "Modern 🏢",
    ],
    "Site Type": [
      "Ruins 🧱",
      "Museum 🖼️",
      "Landmark 🏛️",
      "Heritage Site 🏰",
      "Archaeological Site 🗿",
    ],
    "Tour Type": [
      "Guided Tour 🗣️",
      "Self-guided 🚶",
      "Audio Tour 🎧",
      "Interactive 📱",
      "Educational 📚",
    ],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Evening 🌆", "All Day 🌞"],
  },
  museums: {
    "Museum Type": [
      "Art 🎨",
      "History 🏛️",
      "Science 🔬",
      "Technology 💻",
      "Natural History 🦕",
    ],
    "Collection Focus": [
      "Fine Art 🖼️",
      "Antiquities 🏺",
      "Contemporary 🎭",
      "Local Culture 🌍",
      "Special Exhibits 🎪",
    ],
    "Tour Type": [
      "Guided Tour 🗣️",
      "Audio Guide 🎧",
      "Interactive 📱",
      "Educational 📚",
      "Self-guided 🚶",
    ],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Evening 🌆", "All Day 🌞"],
  },
  culture: {
    "Experience Type": [
      "Performances 🎭",
      "Cooking Class 🧑‍🍳",
      "Music 🎶",
      "Dance 💃",
      "Crafts 🎨",
    ],
    "Local Focus": [
      "Traditional 🧺",
      "Modern 🎨",
      "Festivals 🎉",
      "Community 🤝",
      "Religious 🕍",
    ],
    "Activity Level": [
      "Observational 👀",
      "Interactive 👂",
      "Hands-on ✋",
      "Participatory 🤝",
    ],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Evening 🌆", "Night 🌙"],
  },
  foodie: {
    Cuisine: [
      "Local 🍽️",
      "Italian 🇮🇹",
      "Japanese 🇯🇵",
      "Mexican 🇲🇽",
      "Fusion 🌮",
    ],
    "Experience Type": [
      "Fine Dining 🍽️",
      "Cooking Class 🧑‍🍳",
      "Food Tour 🚚",
      "Market Visit 🛍️",
      "Street Food 🥘",
    ],
    "Dietary Options": [
      "Vegetarian 🌱",
      "Vegan 🌿",
      "Gluten-free 🌾",
      "Seafood 🐟",
      "All Options 🍽️",
    ],
    "Price Range": [
      "Budget 💲",
      "Moderate 💲💲",
      "Upscale 💲💲💲",
      "Fine Dining 💲💲💲💲",
    ],
  },
  sightseeing: {
    "Tour Type": [
      "Walking Tour 🚶",
      "Bus Tour 🚌",
      "Bicycle Tour 🚲",
      "Boat Tour ⛵",
      "Helicopter Tour 🚁",
    ],
    "Area Focus": [
      "Historic District 🏛️",
      "Modern City 🏙️",
      "Natural Scenery 🏞️",
      "Architecture 🏰",
      "Local Life 🏘️",
    ],
    "Tour Style": [
      "Guided 🗣️",
      "Self-guided 🚶",
      "Audio Guide 🎧",
      "Photography 📸",
      "Educational 📚",
    ],
    "Best Time": ["Morning 🌅", "Afternoon ☀️", "Evening 🌆", "Night 🌙"],
  },
  shopping: {
    "Shopping Type": [
      "Local Crafts 🛍️",
      "Art Galleries 🎨",
      "Markets 🏪",
      "Malls 🏬",
      "Boutiques 👗",
    ],
    "Product Focus": [
      "Handicrafts 🎨",
      "Fashion 👗",
      "Antiques 🏺",
      "Local Products 🏺",
      "Souvenirs 🎁",
    ],
    "Shopping Style": [
      "Browsing 👀",
      "Guided Tour 🗣️",
      "Local Experience 🏪",
      "Luxury Shopping 💎",
    ],
    "Price Range": [
      "Budget 💲",
      "Moderate 💲💲",
      "Upscale 💲💲💲",
      "Luxury 💲💲💲💲",
    ],
  },
  nightlife: {
    "Venue Type": [
      "Bar 🍹",
      "Live Music 🎶",
      "Dance Club 💃",
      "Jazz Club 🎷",
      "Rooftop Bar 🌆",
    ],
    "Music Style": [
      "Live Music 🎸",
      "DJ 🎧",
      "Jazz 🎷",
      "Local Music 🎵",
      "International 🎶",
    ],
    Atmosphere: [
      "Relaxed 🛋️",
      "Lively 🎉",
      "Sophisticated 🍸",
      "Local Vibe 🎭",
      "Party 🎊",
    ],
    "Best Time": [
      "Early Evening 🌆",
      "Late Night 🌙",
      "Weekend 🎉",
      "Special Events 🎪",
    ],
  },
};
